name: Build DLL

on:
  pull_request:
    branches: [main,master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce

      - name: Setup conan
        run: pip install conan
        
      - name: Update Plugin Version
        if: github.ref_type == 'tag'
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          (Get-Content -Path "vSMR\SMRPlugin.hpp") -replace '#define MY_PLUGIN_VERSION.*', "#define MY_PLUGIN_VERSION   `"$tag`"" | Set-Content -Path "vSMR\SMRPlugin.hpp"
        shell: pwsh

      - name: Cache Conan (v2)
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2
          key: conan2-${{ runner.os }}-x86-Release-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            conan2-${{ runner.os }}-x86-Release-

      - name: Install dependancies
        run: conan install . -s arch=x86 -s build_type=Release --build=missing --output-folder=build

      - name: Build with cmake
        run: |
          cmake --preset conan-default
          cmake --build --preset conan-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vSMR.dll
          path: build/bin/Release/vSMR.dll

      - name: Upload to Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        if: github.ref_type == 'tag'
        with:
          files: |
            build/bin/Release/vSMR.dll